### PR TITLE
Rubocop performance

### PR DESCRIPTION
**Pull request by artplan1**
follows https://github.com/rtfpessoa/yavdb/pull/9

fixes issues found by `rubocop-performance`

split to separate PR to check with maintainers on style

### CODE REVIEW

**Comment by rtfpessoa** [comment]
I think since some code is mixed, maybe moving code to one would be easier.
Or you could also separate the rspec part from the performance. What do you think?

**Comment by rtfpessoa** [comment]
Can you rebase with master?

**Comment by artplan1** [comment]
fixing in 2 separate PRs is more clear for history
I'll fix conflicts

**Review by rtfpessoa — APPROVED** [review]
LGTM :+1:  Lets wait for the build.

**Comment by rtfpessoa** [comment]
Can you check conflicts?

**Comment by artplan1** [comment]
done :)

**Pull request merged**
